name: Ruby

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'
      - name: Install dependencies
        run: |
          cd 01_base/chapter_III/ebook_store
          gem install bundler
          bundle install
      - name: Run Rubocop
        run: |
          cd 01_base/chapter_III/ebook_store
          bundle exec rubocop
      - name: Run tests
        run: |
          cd 01_base/chapter_III/ebook_store
          bundle exec rspec

