name: Deploy

on:
  push:
    branches:
      - main  # Change to your deployment branch

jobs:
  deploy:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1.0'

      - name: Install dependencies
        run: |
          cd 01_base/chapter_III/ebook_store
          gem install bundler
          bundle install

      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          git remote add heroku https://git.heroku.com/<your-app-name>.git
          git push heroku main
